// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Tue Jan 03 19:31:24 2023

DecodificadorBCD DecodificadorBCD_inst
(
	.Z(Z_sig) ,	// input  Z_sig
	.Y(Y_sig) ,	// input  Y_sig
	.X(X_sig) ,	// input  X_sig
	.W(W_sig) ,	// input  W_sig
	.a(a_sig) ,	// output  a_sig
	.b(b_sig) ,	// output  b_sig
	.c(c_sig) ,	// output  c_sig
	.d(d_sig) ,	// output  d_sig
	.e(e_sig) ,	// output  e_sig
	.f(f_sig) ,	// output  f_sig
	.g(g_sig) 	// output  g_sig
);

